version: 2.1
jobs:
  vcvplugin_docker_build_ubuntu1804_rack2:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run: ./test/build-ubuntu1804-rack2.sh
workflows:
  version: 2
  vcvplugin_build:
    jobs:
      - vcvplugin_docker_build_ubuntu1804_rack2
